### ISSUE TITLE
 Add previous ISC22 Arches submission back to ISC 23 list

### ISSUE THREAD

**Issue by johnlewars** [IO500/submission-data#2]
On May 25, 2023, at 23:19, I reached out to the io500 committee to inform them IBM's "previous ISC22 submission (called ‘Arches’) was removed from the new ISC23 ten node list.  That ISC22 submission used the previous version of the Storage Scale hardware (2 Storage Scale 3200 BBs) and we’d like to keep the submission on the list as a comparison point with the newer Storage Scale 3500 result submitted for ISC23."
 
Andreas Dillinger responded to say he would fix this if I could open an issue to this github: 
>There were a number of submissions that were updates to existing systems and in one of the several times I recreated 
>the list I thought that this one was also a duplicate. 
> 
>Can you please file an issue in GitHubwith the above details, since I believe we need to change the database at this point.

**Comment by adilger** [comment]
Hi Jean Luca, can you please re-add the Arches submission from ISC22 into the ISC23 list. 

Can we just discard the ISC23 list and recreate it via the web interface as we did before the lists were published?

**Comment by johnlewars** [comment]
Hi Andreas and Jean Luca,

Just checking on the status of this issue.  I see that Andreas asked Jean Luca to assist but I haven't seen any update.

Thanks,
John

**Comment by jeanbez** [comment]
@johnlewars apologies for the late reply, we opened a PR to fix this. Please, for future issues open them directly in the https://github.com/IO500/website GitHub so it is easier to track. @adilger can you double check and approve this? It was probably not included a new list has a replacement that was very similar to this submission.
